version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: fxdeal-postgres
    restart: always
    environment:
      POSTGRES_USER: fxuser
      POSTGRES_PASSWORD: fxpass
      POSTGRES_DB: fxdeals
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: fxdeal-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@fx.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  pgdata:
